# Generated by Django 4.2.6 on 2023-10-17 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 17, 18, 27, 53, 286243)),
        ),
    ]
