# Generated by Django 4.2.6 on 2023-10-17 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
